# Generated by Django 5.1.1 on 2024-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="available_seats",
            field=models.IntegerField(default=0),
        ),
    ]
