# Generated by Django 5.1.1 on 2024-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_course_available_course_available_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="available_seats",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="seats",
            field=models.IntegerField(default=0),
        ),
    ]
