# Generated by Django 5.1.1 on 2024-10-06 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_course_available_seats_alter_course_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotarequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="quotarequest",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Approved", "Approved")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
